DROP TABLE IF EXISTS "User";
CREATE TABLE "User" (
    Id INT PRIMARY KEY DEFAULT NEXTVAL('user_id_seq'),
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Username VARCHAR(255),
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS "Order";
CREATE TABLE "Order" (
    Id SERIAL PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UserEmail VARCHAR(255),
    FOREIGN KEY (UserEmail) REFERENCES "User"(Email) ON DELETE SET NULL
);


CREATE TABLE OrderProduct (
    OrderId INT NOT NULL,
    ProductId INT NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES "Order"(Id) ON DELETE CASCADE,
    FOREIGN KEY (ProductId) REFERENCES DT_PRODUCTS(Id) ON DELETE CASCADE,
    PRIMARY KEY (OrderId, ProductId)
);

CREATE TABLE UserOrder (
    UserId INT NOT NULL,
    OrderId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES "User"(Id) ON DELETE CASCADE,
    FOREIGN KEY (OrderId) REFERENCES "Order"(Id) ON DELETE CASCADE,
    PRIMARY KEY (UserId, OrderId)
);
