CREATE TABLE "User" (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Order" (
    Id SERIAL PRIMARY KEY,
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UserEmail VARCHAR(255),
    FOREIGN KEY (UserEmail) REFERENCES "User"(Email) ON DELETE SET NULL
);
