DROP TABLE IF EXISTS DT_PRODUCTS;

CREATE TABLE DT_PRODUCTS (
    name VARCHAR(60) NOT NULL PRIMARY KEY,
    type VARCHAR(60) DEFAULT NULL,
    sizeOfUnit VARCHAR(15) DEFAULT NULL,
    numOfUnits INT DEFAULT 1
);