DROP TABLE IF EXISTS Role;

CREATE TABLE Role (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO Role (Name) VALUES ('ADMIN');
INSERT INTO Role (Name) VALUES ('USER');
