DROP TABLE IF EXISTS "User";
CREATE TABLE "User" (
    Id INT PRIMARY KEY,
    Name VARCHAR(255),
    Email VARCHAR(255) NOT NULL UNIQUE,
    Username VARCHAR(255),
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS "Order";
CREATE TABLE "Order" (
    Id SERIAL PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UserEmail VARCHAR(255),
    FOREIGN KEY (UserEmail) REFERENCES "User"(Email) ON DELETE SET NULL
);
