ALTER TABLE DT_PRODUCTS ADD COLUMN IF NOT EXISTS Id INT AUTO_INCREMENT NOT NULL;

UPDATE DT_PRODUCTS SET Id = (SELECT COUNT(*) FROM DT_PRODUCTS AS temp WHERE temp.name <= DT_PRODUCTS.name);

ALTER TABLE DT_PRODUCTS ADD PRIMARY KEY (Id);

